services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myfastdevdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "myfastdevdb"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.4.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
    - ./core/locust:/mnt/locust
    working_dir: /mnt/locust
    command: -f locustfile.py

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
    env_file:
      - ./core/.env
    ports:
      - "8000:8000"
    command: bash -c 'fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./core:/usr/src/core

volumes:
  postgres_data:
  smtp4dev-data: