FROM python:3.13-slim
WORKDIR /usr/src/core
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*
COPY ./requirements.txt .
RUN python -m venv /venv \
    && /venv/bin/pip install --no-cache-dir --upgrade pip \
    && /venv/bin/pip install --no-cache-dir -r ./requirements.txt
ENV PATH="/venv/bin:$PATH"
COPY ./core .
CMD [ "fastapi", "dev","--host", "0.0.0.0", "--port", "8000" ]