FROM python:3.13-alpine

WORKDIR /usr/src/core
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libpq \
    postgresql-dev \
    bash
COPY ./requirements.txt .
RUN python -m venv /venv \
    && /venv/bin/pip install --no-cache-dir --upgrade pip \
    && /venv/bin/pip install --no-cache-dir -r ./requirements.txt
ENV PATH="/venv/bin:$PATH"
COPY ./core .

# Setup an entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]